
    

security:
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        
    encoders:
        Fallen\FallenBundle\Entity\User: sha512
    providers:
        main:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /admin
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
                
    access_control:
        - { path: ^/admin, roles:[ROLE_USER] }
        - { path: ^/register, roles:[ROLE_USER] }
